Feature/travis to GitHub
CakeDC/auth pull request #61
Opened 2021-05-24 12:11 UTC by steinkel

Use github actions instead of travis

2021-05-25 16:35 UTC, rochamarcelo requested changes
phpcs, phpstan and psalm don't seems to be working

2021-05-25 16:40 UTC, steinkel commented
That's expected, there are many items to fix from these tasks, to be done in the context of another PR, in this PR we've enabled the tasks and set them as continueOnError

2021-05-27 11:25 UTC, rochamarcelo commented
Okay, got it.

2021-05-27 11:29 UTC, rochamarcelo approved these changes

2021-06-18 10:09 UTC, merged