Two factor refactoring.
CakeDC/auth pull request #86
Opened 2024-02-08 22:03 UTC by skie

Extract two factor logic into separate classes  processing each type of 2fa.

2024-02-09 15:14 UTC, steinkel requested changes
Also, please add some docs to cover the changes in configuration and usage

2024-02-09 15:14 UTC, steinkel commented on .github/workflows/ci.yml
> +        php-version: ['7.4', '8.0', '8.1']
add 8.2 and 8.3

2024-02-09 15:14 UTC, steinkel commented on src/Authentication/TwoFactorProcessorInterface.php
> +    public function enabled(): bool;
would it be better to use isEnabled to match with the other methods

2024-02-09 15:14 UTC, steinkel commented on src/Authentication/Webauthn2fAuthenticationCheckerFactory.php
> +        $required = Webauthn2fAuthenticationCheckerInterface::class;
why this change?

2025-03-14 11:13 UTC, skie commented on src/Authentication/Webauthn2fAuthenticationCheckerFactory.php
> +        $required = Webauthn2fAuthenticationCheckerInterface::class;
To match file name and class name. Real file name is Webauthn2fAuthenticationCheckerInterface.php in repo

2025-03-14 11:27 UTC, skie commented
merged to 9.next-cake4 and 10.next-cake5

2025-03-14 11:27 UTC, closed without merging